language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nickdark/docker-react -f Dockerfile.dev .

script:
  - docker run nickdark/docker-react npm run test -- --coverage